### ISSUE TITLE
Left me hanging...

### ISSUE THREAD

**Issue by msmichellegar** [docdis/learn-vagrant#7]
Very handy tutorial! But this bit left me hanging:

"Using vagrant as a VM to run your production OS locally means you..."

So mysterious. Dying to read the rest of the sentence ;)

**Comment by nelsonic** [comment]
:laughing: yeah... it just means you can keep things consistent everywhere...
Feel free to make that sound better and PR. :+1:

**Comment by msmichellegar** [comment]
I will! +1
